global:
  scrape_interval: 15s  # lebih cepat agar responsif saat uji lokal

scrape_configs:
  - job_name: 'titanic_model_exporter'
    scrape_interval: 20s
    scrape_timeout: 10s
    static_configs:
      - targets: ['127.0.0.1:5000']